# Numpy Arrays

## Intro to Numpy Arrays

In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3]

In [4]:
type(my_list)

list

In [5]:
my_arr = np.array(my_list)

In [6]:
type(my_arr)

numpy.ndarray

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0, 100, 1000)

array([  0.        ,   0.1001001 ,   0.2002002 ,   0.3003003 ,
         0.4004004 ,   0.5005005 ,   0.6006006 ,   0.7007007 ,
         0.8008008 ,   0.9009009 ,   1.001001  ,   1.1011011 ,
         1.2012012 ,   1.3013013 ,   1.4014014 ,   1.5015015 ,
         1.6016016 ,   1.7017017 ,   1.8018018 ,   1.9019019 ,
         2.002002  ,   2.1021021 ,   2.2022022 ,   2.3023023 ,
         2.4024024 ,   2.5025025 ,   2.6026026 ,   2.7027027 ,
         2.8028028 ,   2.9029029 ,   3.003003  ,   3.1031031 ,
         3.2032032 ,   3.3033033 ,   3.4034034 ,   3.5035035 ,
         3.6036036 ,   3.7037037 ,   3.8038038 ,   3.9039039 ,
         4.004004  ,   4.1041041 ,   4.2042042 ,   4.3043043 ,
         4.4044044 ,   4.5045045 ,   4.6046046 ,   4.7047047 ,
         4.8048048 ,   4.9049049 ,   5.00500501,   5.10510511,
         5.20520521,   5.30530531,   5.40540541,   5.50550551,
         5.60560561,   5.70570571,   5.80580581,   5.90590591,
         6.00600601,   6.10610611,   6.20620621,   6.30

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(4, 4)

array([[0.52835245, 0.93346055, 0.78704631, 0.53192244],
       [0.57405275, 0.78584633, 0.71643935, 0.45372062],
       [0.99323273, 0.03315729, 0.20190906, 0.31506578],
       [0.74962406, 0.52869963, 0.08718198, 0.39927735]])

In [17]:
np.random.randn(2, 3)

array([[ 0.45493014, -0.14015067, -0.98392259],
       [ 0.26834154, -0.56819117, -0.33262041]])

In [18]:
np.random.randint(1, 88, (4, 5))

array([[21, 84,  9, 74, 52],
       [ 9, 15, 67, 76, 64],
       [58, 63,  9, 54,  7],
       [ 6,  3, 86, 17, 79]], dtype=int32)

In [19]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [20]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr = np.arange(0, 21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [23]:
np.reshape(arr, (3, 7))

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [24]:
random_arr = np.random.randint(0, 101, 10)
random_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52], dtype=int32)

In [25]:
random_arr.max()

np.int32(99)

In [26]:
random_arr.min()

np.int32(2)

In [27]:
random_arr.argmax()

np.int64(5)

In [28]:
random_arr.argmin()

np.int64(7)

In [29]:
random_arr.dtype

dtype('int32')

In [30]:
arr.shape

(21,)

In [31]:
random_arr.shape

(10,)

## Indexing and Selection

In [32]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[8]

np.int64(8)

In [34]:
arr[1:5]

array([1, 2, 3, 4])

In [35]:
arr[:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
arr[0:5] = 100

In [38]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [39]:
arr = np.arange(0, 11)

In [41]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [42]:
slice_of_arr[:] = 99

In [43]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [44]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [45]:
arr_copy = arr.copy()

In [46]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [47]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d.shape

(3, 3)

In [49]:
arr_2d[0]

array([ 5, 10, 15])

In [50]:
arr_2d[2]

array([35, 40, 45])

In [52]:
arr_2d[0, 2]

np.int64(15)

In [55]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [56]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [58]:
bool_arr = arr > 4

In [59]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [60]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [61]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

## Numpy Operations

In [63]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [66]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
arr / arr

C:\Users\Hunter\AppData\Local\Temp\ipykernel_14812\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [68]:
1 / 0

ZeroDivisionError: division by zero

In [69]:
1 / arr

C:\Users\Hunter\AppData\Local\Temp\ipykernel_14812\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [70]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [72]:
np.log(arr)

C:\Users\Hunter\AppData\Local\Temp\ipykernel_14812\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [73]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr.sum()

np.int64(45)

In [75]:
arr.mean()

np.float64(4.5)

In [76]:
arr.max()

np.int64(9)

In [77]:
arr.var()

np.float64(8.25)

In [78]:
arr.std()

np.float64(2.8722813232690143)

In [81]:
arr2d = np.arange(0, 25).reshape(5, 5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
arr2d.shape

(5, 5)

In [83]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
arr2d.sum()

np.int64(300)

In [87]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [88]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])